local_backend: true

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: content/gallery
public_folder: /gallery

logo_url: https://rcsa-new.netlify.app/favicon.ico
site_url: https://rcsa-new.netlify.app
display_url: /

collections:
  - name: boards
    label: Top Boards
    identifier_field: year
    label_singular: Top Board
    description: Top Board Details
    folder: content/boards
    media_folder: "/public/uploads/board"
    public_folder: "/uploads/board"
    create: true
    fields:
      - label: Year
        name: "year"
        widget: number
      - label: Group Photo
        name: group_pic
        widget: "image"
        required: false
      - label: "Office Bearers"
        name: "board"
        widget: list
        fields:
          - { label: "Position", name: "position", widget: "string" }
          - { label: "Name", name: "name", widget: "string" }
          - label: "Photo"
            name: "photo"
            widget: "image"
  - name: projects
    label: Project
    media_folder: "/public/uploads/projects"
    public_folder: "/uploads/projects"
    label_singular: "Project"
    folder: content/projects
    create: true
    nested: { depth: 100 }
    slug: "{{fields.year}}/{{title}}"
    summary: "{{title}} - {{fields.year}}"
    fields:
      - label: Title
        name: title
        widget: string
        default: "Oceania"
      - label: Year
        name: "year"
        widget: number
        default: "2024"
      - label: Description
        name: body
        widget: markdown
      - label: "Committee"
        name: committee
        widget: object
        fields:
          - label: Chairman
            name: chairman
            widget: string
          - label: Secretary
            name: secretary
            widget: string
          - label: Treasurer
            name: treasurer
            widget: string
      - label: Featured Image
        name: image
        widget: image
      - label: "Gallery"
        name: "gallery"
        widget: list
        field:
          label: Source
          name: src
          widget: image
  - name: forms
    label: Forms
    description: Add and edit forms
    folder: content/forms
    create: true
    identifier_field: form_name
    fields:
      - label: "Form Name"
        name: form_name
        widget: string
      - label: Google Spreadsheet ID
        name: g_spreadsheet
        widget: string
      - label: "Form fields"
        name: "fields"
        widget: "list"
        types:
          - label: "Short Text"
            name: "textedit"
            widget: object
            fields:
              - {
                  label: Required,
                  name: required,
                  widget: boolean,
                  default: false,
                  required: false,
                }
              - { label: Label, name: label, widget: string }

              - {
                  label: Placeholder,
                  name: placeholder,
                  widget: string,
                  required: false,
                }
              - {
                  label: Validation Regex,
                  name: regex,
                  widget: string,
                  required: false,
                }
          - label: "Long Text"
            name: "textarea"
            widget: object
            fields:
              - {
                  label: Required,
                  name: required,
                  widget: boolean,
                  default: false,
                  required: false,
                }
              - { label: Label, name: label, widget: string }
              - {
                  label: Placeholder,
                  name: placeholder,
                  widget: string,
                  required: false,
                }
              - {
                  label: Max Letters,
                  name: max,
                  widget: number,
                  required: false,
                  default: 1000,
                }
          - label: "Multiple Choice"
            name: "mcq"
            widget: object
            fields:
              - {
                  label: Required,
                  name: required,
                  widget: boolean,
                  default: false,
                  required: false,
                }
              - { label: Label, name: label, widget: string }
              - label: Type
                name: varient
                widget: "select"
                options: ["radio", "checkbox", "dropdown"]
                default: "radio"
              - label: "Options"
                name: "options"
                widget: list
                field: { label: "Option", name: "option", widget: "string" }
  - name: gallery
    label: Gallery
    description: Upload pictures to the Gallery
    files:
      - label: Pictures
        name: pics
        file: content/gallery.md
        fields:
          - label: "Images"
            name: "piclist"
            widget: list
            fields:
              - label: Image Source
                name: src
                widget: image
                media_folder: "/public/uploads/gallery"
                public_folder: "/uploads/gallery"
              - {
                  label: Home,
                  name: home,
                  widget: boolean,
                  default: false,
                  required: false,
                }
              - { label: Title, name: title, widget: string }
  - name: "config"
    label: "Site Configuration"
    description: Configure settings of the website
    files:
      - label: "Social Links"
        name: social
        file: content/config/social.md
        fields:
          - { label: "Facebook", name: "facebook", widget: string }
          - { label: "Instagram", name: "instagram", widget: string }
          - { label: "X", name: "x", widget: string }
          - { label: "YouTube", name: "youtube", widget: string }
          - { label: "WhatsApp", name: "whatsapp", widget: string }
      - label: Categories
        name: categories
        file: content/config/categories.md
        fields:
          - label: Categories
            name: categories
            widget: list
            field:
              label: "Category"
              name: "category"
              widget: "string"
              pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Not a valid slug"]
      - label: "Home Page Configuration"
        name: homepage
        file: content/config/homepage.md
        fields:
          - label: "Number of projects to show in slider"
            name: "projects"
            widget: "number"
          - label: "Number of posts to show in slider"
            name: "posts"
            widget: "number"
      - label: "Form Configuration"
        name: form
        file: content/config/form.md
        fields:
          - label: Service Account Email
            name: "service_acc_email"
            widget: string
          - label: "Private Key"
            name: "private_key"
            widget: text
          - label: Sign Up Form
            name: "signup_form"
            widget: relation
            collection: forms
            value_field: "form_name"
            search_fields: ["form_name"]
  - name: "banners"
    label: "Banners"
    description: Banner 1 and Banner 2
    files:
      - label: "Banner 1"
        name: "banner-1"
        file: "content/banners/banner-1.md"
        fields:
          - { label: "Show", name: "show", widget: "boolean", default: true }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Text", name: "text", widget: "text" }
          - label: "Button"
            name: "button"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Open in New Tab", name: "newtab", widget: "boolean" }
          - label: Image
            name: image
            widget: image
            media_folder: /content/banners
            public_folder: ""
      - label: "Banner 2"
        name: "banner-2"
        file: "content/banners/banner-2.md"
        fields:
          - { label: "Show", name: "show", widget: "boolean", default: true }
          - { label: "Text", name: "text", widget: "text" }
          - label: "Buttons"
            name: "buttons"
            widget: "object"
            fields:
              - label: "Button 1"
                name: "button1"
                widget: "object"
                fields:
                  - label: "Text"
                    name: "text"
                    widget: "string"
                    required: false
                  - label: "Link"
                    name: "link"
                    widget: "string"
                    required: false
                  - label: "Open in New Tab"
                    name: "newtab"
                    widget: "boolean"
                    required: false
                    default: false
              - label: "Button 2"
                name: "button2"
                widget: "object"
                fields:
                  - label: "Text"
                    name: "text"
                    widget: "string"
                    required: false
                  - label: "Link"
                    name: "link"
                    widget: "string"
                    required: false
                  - label: "Open in New Tab"
                    name: "newtab"
                    widget: "boolean"
                    required: false
                    default: false
